---
title: "Comparing different methods"
date: last-modified
format:
    html:
        embed-resources: true
title-block-banner: true
bibliography: references.bib
---

-   We can use the networks that we built from the previous section and showcase how they (maybe) are giving way different metrics (telling different stories)

-   I think if we have multiple networks for different time points as well we can compare within and between network differences? (need to have a think on that)

```{r}
#| echo: false
#| warning: false

library(dplyr)
library(ggradar)
library(patchwork)
library(readr)
library(scales)
library(tidyverse)

df = list.files(path="data/processed/", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows %>% 
        # to get the ratio
        mutate(ratio = top/basal,
                top = NULL,
                basal = NULL) %>%
        pivot_longer(
            cols = -c(id, model), 
            names_to = "stat",
            values_to = "stat_val")

```

Plot things...

```{r}
#| label: fig-line
#| fig-cap: "Comparing the different structures that are recovered by the different models (colours) over a time series"


ggplot(df) +
    geom_line(aes(x = as.numeric(as.factor(`id`)), 
                    y = stat_val, 
                    colour = model)) +
    geom_point(aes(x = as.numeric(as.factor(`id`)), 
                y = stat_val, 
                colour = model)) +
    facet_wrap(vars(stat),
                scales = 'free') +
    scale_size(guide = 'none') +
    theme_classic() +
    xlab("time") +
    ylab("value") +
    theme(panel.border = element_rect(colour = 'black',
                                      fill = "#ffffff00"),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank())

```