---
title: "Structure vs Function"
date: last-modified
format:
    html:
        embed-resources: true
title-block-banner: true
bibliography: references.bib
---

Linking structure and function to ecological processes

## Section Overview

-   What do we mean by structure = a way in which we are 'summarising' the network.

-   What do we mean by form? (probably nebulous and poorly articulated in general, or at least not explicitly backed by firm eco theory)

    -   species vs system?

-   But does form (structure) = function??

-   Also does the form-function link differ when thinking of bipartite/unipartite systems? I'm inclined to think that many of the ways in which we measure form has been developed in the context of bipartite systems and is there really an ecological reason that they will hold in unipartite systems?

-   See also @thompson2012 and @guimarães2020

## Measuring networks at 'scales'

@delmas2019 gives a somewhat extensive overview of the different ways in which we can 'summarise' network properties (something akin to statistical moments) which is summarised in @tbl-summaries. Importantly we need to acknowledge that these summary statistics are 'retrieved' at different levels of organisation (scale) within the network. For example the in-degree is something that is determined on a by-species level, but connectance is at the network level.

| Summary Statistic (form)  | What                                                                                     | Ref                     | Ecological interpretation (function)                | Scale (I like this idea and want to push it further) |
|---------------|---------------|---------------|---------------|---------------|
| Specificity               | Related to number of links at the species level                                          |                         | Measure of (diet) specialisation                    | Micro (what do species do?)                          |
| Generaility/vulnerability | Number of prey/predators                                                                 | @schoener1989           | Position in food web *e.g.,* top/basal species      | Micro (what do species do?)                          |
| In/out degree             | Number of predators/prey but in a different context??                                    | @williams2000           |                                                     |                                                      |
| Degree distribution       | measures the probability (*P(k))* that a species has *k* interactions within the network |                         |                                                     | Micro (what do species do?)                          |
| Centrality                |                                                                                          |                         | Position of species in network. The idea of hubs... | Macro (how does the community look?)                 |
| Motifs/graphlets          | Smaller interacting units/patterns between 3 species                                     | @milo2002               |                                                     | Meso (how do species interact?)                      |
| Shortest path             | Shortest path from species *a* to a basal species                                        |                         | diameter, perturbation, food chain length           | Meso (how do species interact?)                      |
| Links                     | Number of links in the network                                                           |                         |                                                     | Macro (how does the community look?)                 |
| Connectance               | The number realised links compared to the number of potential links                      |                         |                                                     | Macro (how does the community look?)                 |
| Nestedness                | Interactions forming a subset of others - diets being subsets of others                  | @bastolla2009           |                                                     | Macro (how does the community look?)                 |
| Clustering/modularity     | Non-interacting units/clusters of species (opposite of nestedness?)                      |                         |                                                     | Macro (how does the community look?)                 |
| Intervaility              | 'ordination' of a network. How much can the network be described by a single trait       |                         |                                                     | Macro (how does the community look?)                 |
| Complexity                | A representation of links between species in a system                                    | @strydom2021, @riva2023 |                                                     | Macro (how does the community look?)                 |
| $\beta$-diversity         |                                                                                          | @poisot2012             |                                                     | Meta (how do communities differ?)                    |

: Table with network summary statistics. {#tbl-summaries}

## What do we want to learn from networks?

This is probably just going to churn up thoughts of existential dread...

## References {.unnumbered}

::: {#refs}
:::