project:
  type: website
  output-dir: docs

website:
  title: "Paleo-linked methods for network reconstruction"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Rationale"
        contents:
          - index.qmd
      - section: "(Re)constructing paleo networks"
        contents:
        - 01_reconstruction_methods.qmd
        - section: "Methods"
          contents:
            - 01_bodymass_ratio.qmd
            - 01_expert_knowledge.qmd
            - 01_PFIM.qmd
            - 01_contemporary.qmd
            - 01_niche.qmd
            - 01_adbm.qmd
        - 01_compare.qmd
      - section: "Downsampling"
        contents:
          - 02_downsampling.qmd
      - section: "Form vs Function"
        contents:
          - 03_structure.qmd


author:
  - name: Tanya Strydom
    orcid: 0000-0001-6067-1349
  - name: Friends

format:
    html:
        embed-resources: true
title-block-banner: true

execute:
  freeze: auto