project:
  type: website
  output-dir: docs

website:
  title: "Paleo-linked methods for network reconstruction"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Rationale"
        contents:
          - index.qmd
      - section: "(Re)constructing paleo networks"
        contents:
          - reconstruction_methods.qmd
          - expert_knowledge.qmd
          - PFIM.qmd
          - bodymass_ratio.qmd
      - section: "Form vs Function"
        contents:
          - structure_vs_form.qmd
      - section: "Downsampling"
        contents:
          - meta_vs_realised.qmd

format:
    html:
        embed-resources: true
title-block-banner: true